GDAL & GEOS should use cmake, closes #458
rocker-org/rocker-versioned2 pull request #564
Opened 2022-11-13 04:57 UTC by cboettig

2022-11-13 09:30 UTC, eitsupi requested changes
Sorry, but I have not been able to do any local build testing, I think I should add it to CI, but am afraid to do so because it takes too long to build.

2022-11-13 09:30 UTC, eitsupi commented on scripts/experimental/install_dev_osgeo.sh
> +wget -q http://download.osgeo.org/geos/geos-${GEOS_VERSION}.tar.bz2
Is this change necessary? (I believe it needs to be enclosed in at least double quotes)

2022-11-13 09:30 UTC, eitsupi commented on scripts/experimental/install_dev_osgeo.sh
> -rm geos*tar
If I remove this line, won't the tar file remain?

2022-11-13 09:30 UTC, eitsupi commented on scripts/experimental/install_dev_osgeo.sh
> -rm gdal.tar.gz
Is this line no longer needed?

2022-11-14 15:10 UTC, cboettig commented
@eitsupi looks like linter is now happy and it passes the simple test of being able run the builder without error on rocker/r-ver (see https://github.com/rocker-org/rocker-versioned2/actions/runs/3458693351) which takes about an hour to compile all three elements from source.  

I had to tweak the helper function for detecting `latest` download blobs to avoid getting two URL hits at once, which caused an error.  

Let me know what you think & thanks again for the review & suggestions!

2022-11-15 14:00 UTC, eitsupi approved these changes
Thank you for working on this.
Sorry I can't give you a sufficient review as I understand very little about the build, but thanks to your addition of CI it seems to be working fine!

I modified the CI definition to be the same as the other CI definitions and modified the scripts slightly.

2022-11-15 14:07 UTC, eitsupi commented on scripts/experimental/install_dev_osgeo.sh
> +    wget -qO- "https://api.github.com/repos/$1/releases/latest" | grep -oP "(?<=\"browser_download_url\":\s\")https.*\.tar.gz(?=\")" | grep -v "test"
It seems to me that using the string `test` here is not a good way to convey the intent, so `head -n 1` seems a better choice.

2022-11-15 19:23 UTC, merged